### PR TITLE
Add Github actions to test and automate the process of converting questions.json to the README

### PR DESCRIPTION
**Pull request by maxisme**

### CODE REVIEW

**Comment by VGraupera** [comment]
Thank you! Very cool

**Comment by VGraupera** [comment]
Encountering an error. 

Merge_pull_request__6_from_maxisme_master_·_VGraupera_1on1-questions_9d62d0c

**Comment by maxisme** [comment]
@VGraupera yes it will fail if there has been no change to the `questions.json` as that means there is:

> nothing to commit. 

I can silence the failure if you want?

**Comment by VGraupera** [comment]
Oh, I wasn't clear it had worked. If you are sure the error is OK to ignore then yes. I've read about GitHub actions but had not used it before. I temporarily reverted the PR. I think this is a very clever idea of yours to use actions to update automatically.

**Comment by maxisme** [comment]
yeah basically only commits that include a change to `questions.json` will "pass". It is only a graphical thing if it "fails" anyway 🙂. But up to you!

**Comment by VGraupera** [comment]
I love this idea, but it would IMHO be nice if it didnt "fail" in that scenario. I wonder if there is a way to deal with that.

**Comment by VGraupera** [comment]
@maxisme  I think I figured this out, https://github.com/VGraupera/1on1-questions/commit/3b784d2e56fd46334b432a8de57aedf1b5f9d1d2 

I added this 

```
# git commit if there's any change
 if test -n "$(git status --porcelain 2>/dev/null)"; then`` 
fi
```

**Pull request merged**
